### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by luleyleo** [Finnerale/druid-enums#1]
- [x] complain about missing variants
- [x] default variants
- [x] tuple variants
- [ ] generics (requires new Druid release)
- [ ] documentation of the derive
- [ ] generating documentation for the `...Matcher` widget and its builders
- [ ] add tests
- [ ] ensure consistency with the guarantees Druid offers to widgets
     (e.g. `LifeCycle::WidgetAdded` as first event)
- [ ] bullet proving error messages
- [ ] nitpicking about implementation details
- [ ] think about making Druid a dependency
- [ ] allow shared data like `List` does
- [ ] getting this into Druid
